Repository stolostron/managedcluster-import-controller, pull requests merged in 2021-05, with the labels that each got.

#46 Add management workload annotations
  pkg/bindata/bindata_generated.go
  resources/klusterlet/namespace.yaml
  resources/klusterlet/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test

#47 Upgrade to go1.16
  go.mod
Labels: approved, dco-signoff: yes, lgtm

#49 Add node permission in for klusterlet role
  pkg/bindata/bindata_generated.go
  resources/klusterlet/cluster_role.yaml
Labels: approved, dco-signoff: yes, lgtm

#50 put v1 in the crds.yaml
  pkg/controller/managedcluster/import_secret.go
Labels: approved, dco-signoff: yes, lgtm

#51 Rollback v1
  pkg/controller/managedcluster/import_secret.go
Labels: approved, dco-signoff: yes, lgtm

#52 Do not delete ns with non curator pod
  pkg/controller/managedcluster/import_secret.go
  pkg/controller/managedcluster/managedcluster_controller.go
Labels: approved, dco-signoff: yes, do-not-merge/hold

#53 Add CSR delete/generic predicate
  pkg/controller/csr/csr_manager.go
Labels: approved, dco-signoff: yes, lgtm

#54 update hive api
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#55 Remove imagePullSecret from klusterlet
  pkg/bindata/bindata_generated.go
  resources/klusterlet/klusterlet.yaml
Labels: approved, dco-signoff: yes, lgtm

#56 reduce reconcile time
  pkg/controller/managedcluster/managedcluster_controller.go
Labels: approved, dco-signoff: yes, lgtm

#57 Use Patch to add finalizer
  pkg/controller/managedcluster/managedcluster_controller.go
Labels: approved, dco-signoff: yes, lgtm
