Repository stolostron/managedcluster-import-controller, pull requests merged in 2024-11, with the labels that each got.

#404 Add bootstrap-kubeconfig of current hub as the last one in the list.
  pkg/bootstrap/render.go
  pkg/bootstrap/render_test.go
Labels: lgtm, approved, dco-signoff: yes

#406 🐛 Prevent deletion of cluster namespace when hostingcluster exists
  build/setup-kind-clusters.sh
  cmd/manager/main.go
  deploy/base/clusterrole.yaml
  go.mod
  go.sum
  pkg/controller/clusternamespacedeletion/controller.go
  pkg/controller/clusternamespacedeletion/controller_test.go
  pkg/controller/clusternamespacedeletion/manager.go
  pkg/controller/clusternamespacedeletion/suite_test.go
  pkg/helpers/helpers.go
  test/e2e/resources/hypershift/hostedclusters-Default.crd.yaml
  test/e2e/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#411 [backplane-2.4] konflux: purge managedcluster-import-controller
  .tekton/managedcluster-import-controller-pull-request.yaml
  .tekton/managedcluster-import-controller-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#414 Fix typo `regitration` to `registration`
  build/setup-import-controller.sh
  deploy/agentregistration/clientclusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#409 🐛 [backplane-2.6] Prevent deletion of cluster namespace when hostingcluster exists
  .github/workflows/e2e-tests.yml
  .tekton/managedcluster-import-controller-addon-mce-26-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-26-push.yaml
  build/Dockerfile
  build/Dockerfile.rhtap
  build/setup-kind-clusters.sh
  cmd/manager/main.go
  deploy/base/clusterrole.yaml
  go.mod
  go.sum
  pkg/controller/clusternamespacedeletion/controller.go
  pkg/controller/clusternamespacedeletion/controller_test.go
  pkg/controller/clusternamespacedeletion/manager.go
  pkg/controller/clusternamespacedeletion/suite_test.go
  pkg/helpers/helpers.go
  test/e2e/resources/hypershift/hostedclusters-Default.crd.yaml
  test/e2e/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#410 🐛 [backplane-2.5] Prevent deletion of cluster namespace when hostingcluster exists
  .github/workflows/e2e-tests.yml
  .tekton/managedcluster-import-controller-addon-mce-25-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-25-push.yaml
  build/Dockerfile
  build/Dockerfile.rhtap
  build/setup-kind-clusters.sh
  cmd/manager/main.go
  deploy/base/clusterrole.yaml
  go.mod
  go.sum
  pkg/controller/clusternamespacedeletion/controller.go
  pkg/controller/clusternamespacedeletion/controller_test.go
  pkg/controller/clusternamespacedeletion/manager.go
  pkg/controller/clusternamespacedeletion/suite_test.go
  pkg/helpers/helpers.go
  test/e2e/e2e_suite_test.go
  test/e2e/resources/hypershift/hostedclusters-Default.crd.yaml
  test/e2e/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#417 Upgrade hive apis in Train 21
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#388 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/managedcluster-import-controller-addon-mce-26-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-26-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#387 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/managedcluster-import-controller-addon-mce-25-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-25-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#416 Refactor: controller `AddToManager`
  pkg/controller/autoimport/autoimport_controller.go
  pkg/controller/autoimport/manager.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/manager.go
  pkg/controller/clusternamespacedeletion/controller.go
  pkg/controller/clusternamespacedeletion/manager.go
  pkg/controller/clusternamespacedeletion/suite_test.go
  pkg/controller/controller.go
  pkg/controller/csr/manager.go
  pkg/controller/hosted/controller.go
  pkg/controller/hosted/manager.go
  pkg/controller/importconfig/importconfig_controller.go
  pkg/controller/importconfig/manager.go
  pkg/controller/importstatus/importstatus_controller.go
  pkg/controller/importstatus/manager.go
  pkg/controller/managedcluster/managedcluster_controller.go
  pkg/controller/managedcluster/manager.go
  pkg/controller/manifestwork/manager.go
  pkg/controller/manifestwork/manifestwork_controller.go
  pkg/controller/selfmanagedcluster/manager.go
  pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go
Labels: lgtm, approved, dco-signoff: yes

#412 🐛 [backplane-2.6] fix validate empty CA issue
  pkg/controller/importconfig/cluster_info.go
  pkg/controller/importconfig/cluster_info_test.go
Labels: lgtm, approved, dco-signoff: yes

#421 Refactor csr controller to prepare extend more checks(for example, check if a csr is from flightctl device)
  pkg/controller/csr/csr_controller.go
  pkg/controller/csr/csr_controller_test.go
  pkg/controller/csr/manager.go
Labels: lgtm, approved, dco-signoff: yes

#422 add qps and burst options
  cmd/manager/main.go
Labels: lgtm, approved, dco-signoff: yes

#426 Move `FliesToObjects` function into the `helper` pkg.
  pkg/bootstrap/render.go
  pkg/helpers/helpers.go
Labels: lgtm, approved, dco-signoff: yes

#427 refactor to simplify the bootstrap kubeconfig creation logic
  pkg/bootstrap/bootstrapkubeconfig.go
  pkg/bootstrap/bootstrapkubeconfig_test.go
  pkg/controller/agentregistration/server.go
  pkg/controller/importconfig/cluster_info.go
  pkg/controller/importconfig/cluster_info_test.go
  pkg/controller/importconfig/importconfig_controller.go
Labels: lgtm, approved, dco-signoff: yes

#428 Refactor: move common functions out of csr controller, into `constants` or `helpers`.
  pkg/constants/constants.go
  pkg/controller/controller.go
  pkg/controller/csr/csr_controller.go
  pkg/controller/csr/csr_controller_test.go
  pkg/controller/csr/manager.go
  pkg/helpers/csr.go
  pkg/helpers/csr_test.go
Labels: lgtm, approved, dco-signoff: yes

#432 Fix: make build-image-amd64 to load image from cache to disk.
  Makefile
Labels: dco-signoff: yes
