Repository stolostron/managedcluster-import-controller, pull requests merged in 2025-05, with the labels that each got.

#660 Upgrade Hive API to latest version for train 27
  go.mod
  go.sum
Labels: approved, dco-signoff: yes

#663 Update e2e-tests workflow to ignore .tekton paths and format branch l…
  .github/workflows/e2e-tests.yml
Labels: dco-signoff: yes

#664 Enhance e2e-tests workflow to exclude .tekton paths and improve branc…
  renovate.json
Labels: dco-signoff: yes

#662 Fix konflux issue.
  .tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
  build/Dockerfile.rhtap
Labels: lgtm, approved, dco-signoff: yes

#649 remove the auto-import retry limit
  pkg/constants/constants.go
  pkg/controller/autoimport/autoimport_controller.go
  pkg/controller/autoimport/autoimport_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go
  pkg/helpers/autoimport.go
  pkg/helpers/autoimport_test.go
  test/e2e/autoimport_test.go
  test/e2e/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#659 Update dependencies and refactor klusterlet configuration handling
  go.mod
  go.sum
  pkg/bootstrap/render.go
  pkg/bootstrap/render_test.go
  pkg/controller/importconfig/klusterletconfighandler.go
  pkg/controller/importconfig/klusterletconfighandler_test.go
  vendor/github.com/stolostron/cluster-lifecycle-api/helpers/klusterletconfig/merge.go
  vendor/github.com/stolostron/cluster-lifecycle-api/klusterletconfig/v1alpha1/config.open-cluster-management.io_klusterletconfigs.crd.yaml
  vendor/github.com/stolostron/cluster-lifecycle-api/klusterletconfig/v1alpha1/types.go
  vendor/github.com/stolostron/cluster-lifecycle-api/klusterletconfig/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/stolostron/cluster-lifecycle-api/klusterletconfig/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes

#679 Disable indirect go dependencies in Renovate configuration
  renovate.json
Labels: dco-signoff: yes

#678 fix userName in csr is incorrect if cluster name is long
  pkg/bootstrap/bootstrapkubeconfig.go
  pkg/bootstrap/bootstrapkubeconfig_test.go
  pkg/bootstrap/render.go
  pkg/controller/csr/csr_controller.go
  pkg/controller/csr/csr_controller_test.go
  pkg/controller/importconfig/cluster_info.go
  pkg/helpers/csr.go
  pkg/helpers/csr_test.go
Labels: lgtm, approved, dco-signoff: yes

#677 force clean up resources if cluster is deleting and not accepted
  pkg/controller/resourcecleanup/resourcecleanup_controller.go
  pkg/controller/resourcecleanup/resourcecleanup_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#680 Update sonar configuration.
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#694 fix crd work is force deleted issue
  pkg/controller/resourcecleanup/resourcecleanup_controller.go
  pkg/controller/resourcecleanup/resourcecleanup_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#693 support AutoImportStrategy
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/controller/autoimport/autoimport_controller.go
  pkg/controller/autoimport/autoimport_controller_test.go
  pkg/controller/autoimport/manager.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/manager.go
  pkg/controller/controller.go
  pkg/controller/selfmanagedcluster/manager.go
  pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go
  pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go
  pkg/helpers/autoimport.go
  pkg/helpers/autoimport_test.go
  pkg/helpers/testing/testinghelpers.go
  pkg/source/source.go
  test/e2e/autoimport_test.go
  test/e2e/clusterdeployment_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/klusterletconfig_test.go
  test/e2e/selfmanagedcluster_test.go
  test/e2e/util/util.go
  vendor/github.com/stolostron/cluster-lifecycle-api/constants/constants.go
  vendor/modules.txt
Labels: lgtm, approved, dco-signoff: yes

#698 Add multiarch build support to Tekton pipelines
  .tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
Labels: approved, dco-signoff: yes

#699 🌱 Update ocm api
  go.mod
  go.sum
  vendor/modules.txt
  vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1/types.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/0000_02_clusters.open-cluster-management.io_placements.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1beta1/types_placement.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/feature/feature.go
  vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
  vendor/open-cluster-management.io/api/operator/v1/types_klusterlet.go
  vendor/open-cluster-management.io/api/operator/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/api/work/v1alpha1/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml
  vendor/open-cluster-management.io/api/work/v1alpha1/types_manifestworkreplicaset.go
  vendor/open-cluster-management.io/api/work/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/open-cluster-management.io/ocm/deploy/klusterlet/chart/klusterlet/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
Labels: lgtm, approved, dco-signoff: yes

#701 Update: ginkgo.time to 2h.
  Makefile
Labels: lgtm, approved, dco-signoff: yes

#700 Refactor ImportHelper: Remove applyResourcesFunc field and update related methods
  pkg/helpers/autoimport.go
Labels: lgtm, approved, dco-signoff: yes

#704 Upgrade Hive API to latest version for Train 28
  go.mod
  go.sum
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/nutanix/doc.go
  vendor/github.com/openshift/hive/apis/hive/v1/nutanix/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/nutanix/platform.go
  vendor/github.com/openshift/hive/apis/hive/v1/nutanix/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/modules.txt
Labels: approved, dco-signoff: yes

#703 chore(deps): update GitHub Actions to latest versions for checkout, Go setup, and kubectl
  .github/workflows/e2e-tests.yml
Labels: approved, dco-signoff: yes
