Repository stolostron/managedcluster-import-controller, pull requests merged in 2025-08, with the labels that each got.

#732 🌱 shorten the e2e consistently check time
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#760 Add backup label for external managed kubeconfig in local clusters
  pkg/controller/hosted/controller.go
  pkg/controller/hosted/manifests/external_managed_secret.yaml
Labels: lgtm, approved, dco-signoff: yes

#765 🐛 [bp-2.9] Set OCM VERSION for e2e
  .github/workflows/e2e-tests.yml
Labels: lgtm, approved, dco-signoff: yes

#767 🐛 [bp-2.7] Set OCM VERSION for e2e
  .github/workflows/e2e-tests.yml
  build/setup-ocm.sh
Labels: lgtm, approved, dco-signoff: yes

#768 🐛 [bp-2.8] Set OCM VERSION for e2e
  .github/workflows/e2e-tests.yml
  build/setup-ocm.sh
Labels: lgtm, approved, dco-signoff: yes

#772 Fix .tekton PipelineRun pathInRepo for backplane-2.8 branch
  .tekton/managedcluster-import-controller-addon-mce-28-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-28-push.yaml
Labels: approved, dco-signoff: yes

#776 Add multi-platform build support and Slack notifications to Tekton pipelines
  .tekton/managedcluster-import-controller-addon-mce-28-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-28-push.yaml
Labels: approved, dco-signoff: yes

#777 Add missing tekton pipeline parameters for backplane-2.9
  .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
Labels: approved, dco-signoff: yes

#778 Upgrade Hive APIs to master branch
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes

#780 Add TRIGGER_BUILD file to trigger CI builds
  TRIGGER_BUILD
Labels: dco-signoff: yes

#781 Update TRIGGER_BUILD timestamp to trigger CI builds
  TRIGGER_BUILD
Labels: dco-signoff: yes

#784 Update TRIGGER_BUILD timestamp to trigger CI builds
  TRIGGER_BUILD
Labels: dco-signoff: yes
