Repository stolostron/managedcluster-import-controller, pull requests merged in 2025-07, with the labels that each got.

#735 setup konflux for mce 2.10
  .tekton/managedcluster-import-controller-addon-mce-210-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-210-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#737 Fix klusterlet 2.13 CR doesn't match 2.14 CRD in globalhub's no-operator case.
  go.mod
  go.sum
  pkg/bootstrap/render.go
  pkg/bootstrap/render_test.go
  pkg/controller/importconfig/klusterletconfighandler_test.go
Labels: approved, dco-signoff: yes, AI-assisted

#742 Update common pipeline to mce-2.10.
  .tekton/managedcluster-import-controller-addon-mce-210-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-210-push.yaml
Labels: approved, dco-signoff: yes

#745 Remove sleep 100 from setup-kind-clusters.sh
  build/setup-kind-clusters.sh
Labels: approved, dco-signoff: yes

#750 add an annotation to prevent the cluster ns from being deleted
  pkg/constants/constants.go
  pkg/controller/clusternamespacedeletion/controller.go
  pkg/controller/clusternamespacedeletion/controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#756 should delete hosting manifestworks after there is no hosting addons
  pkg/controller/resourcecleanup/resourcecleanup_controller.go
  pkg/controller/resourcecleanup/resourcecleanup_controller_test.go
Labels: lgtm, approved, dco-signoff: yes
