Repository stolostron/managedcluster-import-controller, pull requests merged in 2025-06, with the labels that each got.

#713 Refactor: remove unused makefile commands.
  Makefile
Labels: approved, dco-signoff: yes

#714 Add a github action to clean stale branches.
  .github/workflows/cleanup-stale-branches.yml
Labels: approved, dco-signoff: yes

#715 Fix: clean up branches script.
  .github/workflows/cleanup-stale-branches.yml
Labels: dco-signoff: yes

#716 Add more logs during branch clean up.
  .github/workflows/cleanup-stale-branches.yml
Labels: dco-signoff: yes

#724 :seedling: [backplane-2.9] update konflux files
  .tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#726 Replace PipelineSpec with PipelineRef in backplane-2.5 tekton files
  .tekton/managedcluster-import-controller-addon-mce-25-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-25-push.yaml
Labels: dco-signoff: yes

#727 Replace PipelineSpec with PipelineRef in backplane-2.6 tekton files
  .tekton/managedcluster-import-controller-addon-mce-26-pull-request.yaml
  .tekton/managedcluster-import-controller-addon-mce-26-push.yaml
Labels: dco-signoff: yes
